// flow-typed signature: e22c3e409ce8906871b5d1e729fe477f
// flow-typed version: <<STUB>>/@material/react-card_v^0.10.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material/react-card'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material/react-card' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material/react-card/dist/card.css' {
  declare module.exports: any;
}

declare module '@material/react-card/dist/card.min.css' {
  declare module.exports: any;
}

declare module '@material/react-card/dist/index' {
  declare module.exports: any;
}

declare module '@material/react-card/dist/index.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material/react-card/dist/card.css.js' {
  declare module.exports: $Exports<'@material/react-card/dist/card.css'>;
}
declare module '@material/react-card/dist/card.min.css.js' {
  declare module.exports: $Exports<'@material/react-card/dist/card.min.css'>;
}
declare module '@material/react-card/dist/index.js' {
  declare module.exports: $Exports<'@material/react-card/dist/index'>;
}
declare module '@material/react-card/dist/index.min.js' {
  declare module.exports: $Exports<'@material/react-card/dist/index.min'>;
}
